
GET http://localhost:8080/home/all

###

GET http://localhost:8080/home/user/1

###

POST http://localhost:8080/home/add
Content-Type: application/json

{
    "name": "ajay",
    "mobileNumber": "822031510",
    "emailAddress": "ajay@gmail.com",
    "dateOfBirth": "2000-05-19",
    "password": "password"
}

###

POST http://localhost:8080/home/add
Content-Type: application/json

{
    "name": "raj",
    "mobileNumber": "9876543210",
    "emailAddress": "raj@gmail.com",
    "dateOfBirth": "1990-02-15",
    "password": "password"
}

###


DELETE http://localhost:8080/home/1

###

PUT http://localhost:8080/home/1?name="raj"

###

POST http://localhost:8080/home/verify
Content-Type: application/json

{
    "mobileNumber": "822031510",
    "password": "pass1word"
}
